# R script for "carob"


carob_script <- function(path) {
   
"Sweetpotato is an important crop in many parts of the world especially in developing countries. It is used for both human consumption as well as livestock feed. It is an important source of carbohydrates, vitamin C, fibre, iron, potassium, protein and β-carotene. Its production is, however, constrained by several biotic and abiotic factors, including pests and diseases, low soil fertility, drought, cold and salinity. Breeding is one of the ways to overcome some of these constraints and in sweetpotato the polycross or controlled cross methods can be used. To determine which of the two methods was more efficient, genotypes generated by both methods were evaluated over two seasons at Namulonge and Kachwekano. The type of cross (polycross or controlled) was significantly (P≤0.05) different for storage root yield, response to sweetpotato virus disease, Alternaria blight, and harvest index (HI). The controlled cross families had a significantly higher mean harvest index of 43.2% than the polycross families with a mean HI of 31.8%. Therefore, controlled crosses could be deployed to systematically increase the HI in sweetpotato breeding populations. Significant (P≤0.05) differences were observed among families for all traits. This stresses that the parents used in a cross are very important in generating genotypes with desired attributes. It was apparent that both the polycross and controlled crosses are good methods for generating new sweetpotato genotypes in a sweetpotato breeding program. Where aggregate performance was considered (selection index) the controlled crosses method produced more (75% of the top 20 desirable genotypes) than the polycross method across the two sites. However, the best three genotypes over the two sites were from the polycross family of Ejumula. Therefore, sweetpotato controlled crosses could be very useful for population improvement using recurrent selection while polycrosses could be suitable for variety development. Both hybridization methods require cautious selection of parents to match the breeding objectives."
   
   uri <- "doi:10.21223/ILCAZ7"
   group <- "varieties_potato" 
   ff  <- carobiner::get_data(uri, path, group)
   
   meta <- data.frame(
      carobiner::get_metadata(uri, path, group, major=1, minor=1), 
      data_organization ="CIP", 
      publication ="doi:10.5539/jas.v11n17p123", 
      project =NA, 
      data_type = "experiment",
      response_vars = "yield;fwy_residue;fwy_total",
      treatment_vars = "variety", 
      carob_contributor = "Cedric Ngakou", 
      carob_date = "2024-09-25",
      notes= NA
   )
   
   f <- ff[grepl("Controlled", basename(ff))]
 
   r <- carobiner::read.excel(f, na= c(".")) 
   
   ### Processing 
   d <- data.frame(
      location= r$site,
      season= r$season,
      treatment= ifelse(grepl("P", r$crosstype)," polycross",
                 ifelse(grepl("C", r$crosstype),"controlled cross", "none")) ,
      variety= r$geno,
      diseases= "alternaria blight",
      disease_severity= as.character(r$alt1),
      virus_severity= as.character(r$vir1),
      severity_scale= "1-9",
      yield= r$RYTHA*1000,
      fwy_residue= r$FYTHA*1000,
      harvest_index= r$HI,
      fwy_total= r$BIOM*1000,
      planting_date= substr(r$season, 1, 4),
      trial_id= paste0(r$site, "-", r$season)
   )

   d$country <- "Uganda"
   d$crop <- "sweetpotato"
   d$on_farm <- TRUE
   d$irrigated <- NA
   d$is_survey <- FALSE
   d$inoculated <- FALSE
   d$yield_part <- "roots"
   
   d$plant_spacing <- 30
   d$row_spacing <-  100 
   
   ## Adding longitude and latitude
   
   d$longitude[d$location=="Kachwekano"] <- 29.9504
   d$longitude[d$location=="Namulong"] <- 32.6182
   d$latitude[d$location=="Kachwekano"] <- -1.2558
   d$latitude[d$location=="Namulong"] <-  0.5357
   
   d$geo_from_source <- FALSE
  
   d$N_fertilizer <- d$P_fertilizer <- d$K_fertilizer <- as.numeric(NA)
   
   ## Removing one duplicate row
   d <- unique(d)
   
   carobiner::write_files (path, meta, d)
}


