---
title: Carob report
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)

scrolltab <- function(data, caption, width="100%") {
  rownames(data) <- NULL
  kableExtra::kbl(data, caption=caption) |>
    kableExtra::kable_classic(full_width = F,  position = "right") |>
    kableExtra::kable_styling(bootstrap_options = c("striped", "hover"))  |> 
    kableExtra::scroll_box(width=width, height="400px")
}

ktab <- function(data, caption) {
    kableExtra::kbl(data, caption=caption) |>
    kableExtra::kable_classic(full_width=FALSE) |> 
    kableExtra::kable_styling(bootstrap_options = c("striped", "hover"))
}

group <- "crop_cuts"

f <- paste0("data/compiled/", group, ".csv")
if (!file.exists(f)) {
  knitr::knit_exit()
}
```

```{r setup2, include=FALSE}
d <- read.csv(f) 
m <- read.csv(gsub(".csv$", "_meta.csv", f))

get_values <- function(x, label) {
  x <- unique(x)
  ifelse(length(x)==1, x, paste0(length(x), " ", label, "(", paste(sort(x), collapse=", "), ")"))
}

crop <- get_values(d$crop, "crops")
country <- get_values(d$country, "countries")

locvars <- c("country", paste0("adm", 1:5), "location", "site", "longitude", "latitude")
i <- which(locvars %in% colnames(d))
locs <- unique(d[, locvars[i]])
if (all(c("longitude", "latitude") %in% colnames(locs))) {
	xy <- unique(locs[, c("longitude", "latitude")])
	xytxt <- paste0("for which we have ", nrow(xy), " unique mapped locations.")
	nrec_noxy <- is.na(d$latitude) | is.na(d$longitude)
	if (any(nrec_noxy)) {
		xytxt <- paste(xytxt, sum(nrec_noxy), "records do not have coordinates.")
	}
	haveXY <- TRUE
} else {
	xytxt <- paste0("for which we have no coordinates.")
	xy <- cbind(0,0)[0,]
	haveXY <- FALSE
}

if (grepl("trials", group)) {
	varieties <- unique(d$variety)
	if (is.null(varieties))	varieties <- unique(d$variety_code)
   vartxt <- paste(" These are trial data for", length(varieties), "varieties.") 
} else {
	vartxt <- ""
}
   
```


This report describes the aggregated data for "*`r group`*". The dataset has `r nrow(d)` records and `r ncol(d)` variables for `r crop` in `r country`. `r vartxt`

</br>
These are the first `r min(nrow(d), 25)` records: 

```{r tab1}
scrolltab(head(d, 25), "records")
```


The observations are for `r nrow(locs)` locations, `r xytxt`

```{r map, include=haveXY}
locs <- locs[!is.na(locs$latitude), ]
if (nrow(locs) > 0) {
  suppressMessages(library(terra))
  crs <- terra::crs
  v <- terra::vect(locs, c("longitude", "latitude"), crs="+proj=longlat")
  terra::plet(v, cex=2, col="red")
}
```

</br>
The data are further summarized in the table below


```{r summary, fig.width=6}
d$longitude <- d$latitude <- NULL
dfs <- summarytools::dfSummary(d, varnumbers=FALSE, graph.magnif=0.75, 
                               max.string.width=20, display.labels=FALSE, valid.col=FALSE, 
							  )
summarytools::view(dfs, method = "render", 
                    report.title="", max.tbl.height = Inf)
```

